services:
    postgres:
        image: postgres:16
        container_name: app_database
        restart: always
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
        ports:
            - '54321:5432'
        volumes:
            - ./.docker/postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
