/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
    [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Hooks {
    correlation_identifier_field: string | null;
    correlation_identifier_location: string | null;
    created_at: Generated<Timestamp>;
    description: string;
    id: string;
    name: string;
}

export interface Webhooks {
    correlation_value: string | null;
    created_at: Generated<Timestamp>;
    headers: Json;
    hook_id: string;
    id: string;
    method: string;
    payload: Json;
    query: Json;
}

export interface DB {
    hooks: Hooks;
    webhooks: Webhooks;
}
